/**
 * Created by xiaoqi on 2016/9/5.
 */

export const LOAD_DOCTOR_LIST='LOAD_DOCTOR_LIST';

export const TOGGLE_DETAIL_DIALOG='TOGGLE_DETAIL_DIALOG';

export const SET_CURRENT_REGISTRATION_INFO='SET_CURRENT_REGISTRATION_INFO';

export const   TOGGLE_USER_HEALTH_DETAIL_DIALOG='TOGGLE_USER_HEALTH_DETAIL_DIALOG';

export const SET_CURRENT_USER_HEALTH_DATA='SET_CURRENT_USER_HEALTH_DATA';

export const SET_PAYMENT_DISEASE='SET_PAYMENT_DISEASE';