exports.types = {
  "css": "text/css",
  "gif": "tempFile/gif",
  "html": "text/html",
  "ico": "tempFile/x-icon",
  "jpeg": "tempFile/jpeg",
  "jpg": "tempFile/jpeg",
  "js": "text/javascript",
  "json": "application/json",
  "pdf": "application/pdf",
  "png": "tempFile/png",
  "svg": "tempFile/svg+xml",
  "swf": "application/x-shockwave-flash",
  "tiff": "tempFile/tiff",
  "txt": "text/plain",
  "wav": "audio/x-wav",
  "wma": "audio/x-ms-wma",
  "wmv": "video/x-ms-wmv",
  "xml": "text/xml"
};